-- Insert categories into the categories table
INSERT INTO categories (name)
VALUES 
    ('super'),
    ('outside food'),
    ('bills'),
    ('aliexpress'),
    ('Bakery'),
    ('clothes'),
    ('Google Storage'),
    ('Gasoline'),
    ('Paybox & BIT'),
    ('parking lot'),
    ('Pizozia'),
    ('Dog Store'),
    ('Books & E-Books'),
    ('Cellular & Internet - (Networking)'),
    ('Netflix'),
    ('Israel Electric'),
    ('Car maintenance'),
    ('maxstock'),
    ('Bars'),
    ('SpotifyIL'),
    ('Resume.IO'),
    ('Super Pharm'),
    ('Wine Store'),
    ('Bikes'),
    ('Car Insurance'),
    ('FREENOW* 971QWJ-2'),
    ('DHL'),
    ('Israel Railways & Kvish 6'),
    ('paypal & GODADDY'),
    ('Cellular Store'),
    ('מחסני חשמל'),
    ('tamir mandovski'),
    ('PAYPAL *NEWENDLESST'),
    ('SP WILDLING SHOES'),
    ('קופי דיל-צמרת'),
    ('Paybox & Ivory'),
    ('Sport Items'),
    ('שילב'),
    ('wishi תל אביב'),
    ('Audible'),
    ('Good Pharm'),
    ('AMZN Mktp US*DQ64S6OW3'),
    ('מדאדס ת.ב בע"מ'),
    ('Udemy'),
    ('העברת חיובים עקב שינוי מועד חיוב'),
    ('Resume.io & AWS EMEA')
ON CONFLICT DO NOTHING; -- Avoids insertion errors for existing entries

-- Insert links into the category_links table using the category IDs
INSERT INTO category_links (international_branch_id, category_id)
VALUES 
    ('5411', (SELECT id FROM categories WHERE name = 'super')),
    ('5499', (SELECT id FROM categories WHERE name = 'super')),
    ('5812', (SELECT id FROM categories WHERE name = 'outside food')),
    ('5814', (SELECT id FROM categories WHERE name = 'outside food')),
    ('9399', (SELECT id FROM categories WHERE name = 'bills')),
    ('9311', (SELECT id FROM categories WHERE name = 'bills')),
    ('5311', (SELECT id FROM categories WHERE name = 'aliexpress')),
    ('5310', (SELECT id FROM categories WHERE name = 'aliexpress')),
    ('5451', (SELECT id FROM categories WHERE name = 'Bakery')),
    ('5462', (SELECT id FROM categories WHERE name = 'Bakery')),
    ('5621', (SELECT id FROM categories WHERE name = 'clothes')),
    ('5651', (SELECT id FROM categories WHERE name = 'clothes')),
    ('5699', (SELECT id FROM categories WHERE name = 'clothes')),
    ('5816', (SELECT id FROM categories WHERE name = 'Google Storage')),
    ('5818', (SELECT id FROM categories WHERE name = 'Google Storage')),
    ('5983', (SELECT id FROM categories WHERE name = 'Gasoline')),
    ('5541', (SELECT id FROM categories WHERE name = 'Gasoline')),
    ('6012', (SELECT id FROM categories WHERE name = 'Paybox & BIT')),
    ('4829', (SELECT id FROM categories WHERE name = 'Paybox & BIT')),
    ('6538', (SELECT id FROM categories WHERE name = 'Paybox & BIT')),
    ('7523', (SELECT id FROM categories WHERE name = 'parking lot')),
    ('5441', (SELECT id FROM categories WHERE name = 'Pizozia')),
    ('5995', (SELECT id FROM categories WHERE name = 'Dog Store')),
    ('5942', (SELECT id FROM categories WHERE name = 'Books & E-Books')),
    ('4812', (SELECT id FROM categories WHERE name = 'Cellular & Internet - (Networking)')),
    ('4899', (SELECT id FROM categories WHERE name = 'Netflix')),
    ('4900', (SELECT id FROM categories WHERE name = 'Israel Electric')),
    ('5521', (SELECT id FROM categories WHERE name = 'Car maintenance')),
    ('5722', (SELECT id FROM categories WHERE name = 'maxstock')),
    ('5813', (SELECT id FROM categories WHERE name = 'Bars')),
    ('5815', (SELECT id FROM categories WHERE name = 'SpotifyIL')),
    ('5817', (SELECT id FROM categories WHERE name = 'Resume.IO')),
    ('5912', (SELECT id FROM categories WHERE name = 'Super Pharm')),
    ('5921', (SELECT id FROM categories WHERE name = 'Wine Store')),
    ('5940', (SELECT id FROM categories WHERE name = 'Bikes')),
    ('6300', (SELECT id FROM categories WHERE name = 'Car Insurance')),
    ('4121', (SELECT id FROM categories WHERE name = 'FREENOW* 971QWJ-2')),
    ('4215', (SELECT id FROM categories WHERE name = 'DHL')),
    ('4789', (SELECT id FROM categories WHERE name = 'Israel Railways & Kvish 6')),
    ('4816', (SELECT id FROM categories WHERE name = 'paypal & GODADDY')),
    ('5045', (SELECT id FROM categories WHERE name = 'Cellular Store')),
    ('5065', (SELECT id FROM categories WHERE name = 'מחסני חשמל')),
    ('5192', (SELECT id FROM categories WHERE name = 'tamir mandovski')),
    ('5331', (SELECT id FROM categories WHERE name = 'PAYPAL *NEWENDLESST')),
    ('5661', (SELECT id FROM categories WHERE name = 'SP WILDLING SHOES')),
    ('5732', (SELECT id FROM categories WHERE name = 'קופי דיל-צמרת')),
    ('5734', (SELECT id FROM categories WHERE name = 'Paybox & Ivory')),
    ('5941', (SELECT id FROM categories WHERE name = 'Sport Items')),
    ('5945', (SELECT id FROM categories WHERE name = 'שילב')),
    ('5947', (SELECT id FROM categories WHERE name = 'wishi תל אביב')),
    ('5968', (SELECT id FROM categories WHERE name = 'Audible')),
    ('5977', (SELECT id FROM categories WHERE name = 'Good Pharm')),
    ('5999', (SELECT id FROM categories WHERE name = 'AMZN Mktp US*DQ64S6OW3')),
    ('7311', (SELECT id FROM categories WHERE name = 'מדאדס ת.ב בע"מ')),
    ('7372', (SELECT id FROM categories WHERE name = 'Udemy')),
    ('7392', (SELECT id FROM categories WHERE name = 'העברת חיובים עקב שינוי מועד חיוב')),
    ('7399', (SELECT id FROM categories WHERE name = 'Resume.io & AWS EMEA'))
ON CONFLICT DO NOTHING; -- Avoids insertion errors for existing entries


INSERT INTO categories (name)
VALUES ('זיכויים')